// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('redditService', []).factory('RedditFactory', function($http) {
    return {
      get: function() {
        return $http.get('http://www.reddit.com/.json').then(function(results) {
          return results.data;
        });
      }
    };
  });

}).call(this);
